#!/bin/bash

#Test process by 07(10000+200+4)

cleanup()
# example cleanup function
{
echo " ctrl+c?"

   for job in `cat pid.${sec}`
do
    /usr/bin/kill -9 $job 

done
rm pid.${sec}
rm locked
ls -lrt  
date
sleep 1

  return $?
}
 
control_c()
# run if user hits control-c
{
  #echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}
 
# trap keyboard interrupt (control-c)
trap control_c SIGINT

doMail()
# run to send mail notifications
{
cat maillist.txt |xargs echo > .mail
  echo -en "\n*** Mailing ***\n"
while read EMAIL_LIST
do
if [ ! -z "$EMAIL_LIST" ]
then
ssh mrte1@10.248.68.122 "source .profile;echo -en $1 '\\n\\nIyi Calismalar\\nAUT' | mailx -s 'ReturnToPrevPatch Hata - Agile Ortami' $EMAIL_LIST"
fi
done < .mail
  
}


mrteid=$(echo $ORGADATA|sed 's/\(.*\)\(.\)/\2/')
if [[ $mrteid -eq 2 ]] 
    then 
	echo mrte1 useriyla calistiriniz
	exit
	
fi
#if [[ -s locked ]]
#then
#echo "script zaten calisiyor."
#exit
#fi
#

if [[ $(ps -ef|grep deploy.shSleep|grep -v grep|grep -v /bin/bash|wc -l) -ne 0 ]]
then
ps -ef|grep deploy.shSleep|grep -v grep
echo
	echo -e "Script ileri tarihte calismak uzere acilmis. Deploya baslamamissa Onu kill ettikten sonra tekrar deneyiniz. kill etmek icin bu komutu kosunuz:\\nps -ef|grep deploy.shSleep|grep -v grep|awk '{print $2}'|xargs /usr/bin/kill"
	exit
fi

if [[ $(ps -ef|grep deploy.sh|grep -v grep|grep -v /bin/bash|wc -l) -ne 0 ]]
then
ps -ef|grep deploy.sh|grep -v grep
	echo "script zaten calisiyor."
	exit
fi



echo locked > locked
 cat maillist.txt |xargs echo > .mail
echo script baslangic: > log
date >> log
echo script baslangic:
date
 

 #notify subscribers
 while read EMAIL_LIST
do
if [ ! -z "$EMAIL_LIST" ]
then
ssh mrte1@10.248.68.122 "source .profile;echo -en \"Starting to ReturnToPrevPatch to Agile Environment from $(grep RTC_TST1_STREAM /rte/orgadata/mrte1/avea/work/AveaRtcScmTools/scripts/rtc_refresh_gold_config.properties) \\n 5 dakika RTEde 10dk BASda kesinti bekleniyor.\"  | mailx -s 'Agile ortamina ReturnToPreviousPatch Basliyor ^_^' $EMAIL_LIST"
fi
done <.mail
 
echo komut:  /tmp/patch/rtc_refresh_gold_config_prev_patch $1 2>&1|tee rtc_refresh_gold_config.log
 /tmp/patch/rtc_refresh_gold_config_prev_patch $1 2>&1|tee rtc_refresh_gold_config.log
#rtc_refresh_gold_config 2>&1|tee rtc_refresh_gold_config.log
echo ---
  ls -lrt $ORGAROOT; ls -lrt $ORGAROOT/si
  
  #önemli bir hata olmadigi halde hata basarsa if den fi ye  7 satiri silip kaldiriniz.
  if [[ $(grep -i 'nvalid password' rtc_refresh_gold_config.log|wc -l) -gt 0 || $(grep :P: rtc_refresh_gold_config.log|wc -l) -gt 0 || $(grep 'ERROR\s:' rtc_refresh_gold_config.log|wc -l) -gt 0 || $(grep -i 'Could not create' rtc_refresh_gold_config.log|wc -l) -gt 0 ]]
then
	echo   "rtc_refresh_gold_config hata verdi galiba. /tmp/deploy/rtc_refresh_gold_config.log dosyasini kontrol ediniz"
	cat rtc_refresh_gold_config.log 
	doMail "rtc_refresh_gold_config hata verdi galiba. /tmp/deploy/rtc_refresh_gold_config.log dosyasini kontrol ediniz"
	cleanup;exit
fi

#cp $ORGAROOT/si/bas/db/cr_property.sql  cr_property.sql.orj
#sed "/setProperty (oid_bas_rte, 'instances', '1,3,5,7');/s|setProperty (oid_bas_rte, 'instances', '1,3,5,7');|setProperty (oid_bas_rte, 'instances', '1,3');|" $ORGAROOT/si/bas/db/cr_property.sql  > tmpdosya
#mv tmpdosya  $ORGAROOT/si/bas/db/cr_property.sql
#diff $ORGAROOT/si/bas/db/cr_property.sql  cr_property.sql.orj
#
#
#scp $ORGAROOT/si/bas/db/cr_property.sql bas@10.248.68.128:/bas/orgaroot/bas/si/bas/db/cr_property.sql
#scp $ORGAROOT/si/bas/db/cr_property.sql mrte2@localhost:/rte/orgaroot/mrte2/si/bas/db/cr_property.sql
#
# ssh bas@10.248.68.128 'source .profile;which sql;  sql bas @ /bas/orgaroot/bas/si/bas/db/cr_property.sql'

 

 sec=$(date +%Y%m%d%H%M%S)
op_date=$(date +%Y%m%d)
#alias l='ls -lrt'
tail -F /rte/orgadata/mrte2/log/OUPMRTELOG_${op_date}.[0-9]*[^gz] > mrte2OUPMLog.txt &
echo $! > pid.$sec   
tail -F /rte/orgadata/mrte1/log/OUPMRTELOG_${op_date}.[0-9]*[^gz] > mrte1OUPMLog.txt&
echo $! >> pid.$sec   
 ssh bas@10.248.68.128 '/usr/local/bin/tail -F /bas/orgadata/bas/log/bascs_01_02/CSLOG' > bascs_01_02_CSLOG.txt&
echo $! >> pid.$sec   
 ssh bas@10.248.68.128 '/usr/local/bin/tail -F /bas/orgadata/bas/log/bascs_01_01/CSLOG' > bascs_01_01_CSLOG.txt&
echo $! >> pid.$sec 

#link degilse cf yi sil
#if [[ $( ls -l $ORGADATA/cnf/reg/scp/zones/cf|grep inss7moc|wc -l) -eq 0 ]]
#then
#echo moving cf 
#mv $ORGADATA/cnf/reg/scp/zones/cf $ORGADATA/cnf/reg/scp
#ssh mrte2@localhost 'source .profile;mv $ORGADATA/cnf/reg/scp/zones/cf $ORGADATA/cnf/reg/scp' 
#fi

echo komut: si-check-orgadata --fix-data --fix-conf --fix-env --fix-struct > mrte1.si-check-orgadata.log 2>&1  
si-check-orgadata --fix-data --fix-conf --fix-env --fix-struct > mrte1.si-check-orgadata.log 2>&1  
hata=$(grep -v ':E:Old entry cnf/reg/scp/zones/cf.old replaced by symlinked should be checked.' mrte1.si-check-orgadata.log|egrep ':E:|:P:'|grep -v ':P:Errors occured in checking $ORGADATA.'|grep -v 'that do not belong here'|wc -l)
hata2=$(grep 'that do not belong here' mrte1.si-check-orgadata.log|wc -l)
if [[ $hata -ne 0||$hata2 -ne 1 ]]
then
	echo   "si-check-orgadata mrte1de hata verdi galiba. kontrol ediniz"
	cat mrte1.si-check-orgadata.log
	doMail "si-check-orgadata mrte1de hata verdi galiba. kontrol ediniz"
	cleanup;exit
fi
cp $ORGADATA/cnf/extComm/config.cfg $ORGADATA/cnf/extComm/config.cfg.si-check-orgadatadanGelen
cp $ORGADATA/cnf/extComm/config.cfg.PRE_060 $ORGADATA/cnf/extComm/config.cfg
echo komut: "ssh mrte2@localhost 'source .profile;si-check-orgadata --fix-data --fix-conf --fix-env --fix-struct ' > mrte2.si-check-orgadata.log 2>&1"
ssh mrte2@localhost 'source .profile;si-check-orgadata --fix-data --fix-conf --fix-env --fix-struct ' > mrte2.si-check-orgadata.log 2>&1
hata=$(grep -v ':E:Old entry cnf/reg/scp/zones/cf.old replaced by symlinked should be checked.' mrte2.si-check-orgadata.log|egrep ':E:|:P:'|grep -v ':P:Errors occured in checking $ORGADATA.'|grep -v 'that do not belong here'|wc -l)
hata2=$(grep 'that do not belong here' mrte2.si-check-orgadata.log|wc -l)
if [[ $hata -ne 0||$hata2 -ne 1 ]]
then
	echo   "si-check-orgadata mrte2de hata verdi galiba. kontrol ediniz"
	cat mrte2.si-check-orgadata.log
	doMail "si-check-orgadata mrte2de hata verdi galiba. kontrol ediniz"
	cleanup;exit
fi

cp $ORGADATA/cnf/extComm/config.cfg $ORGADATA/cnf/extComm/config.cfg.si-check-orgadatadanGelen
cp $ORGADATA/cnf/extComm/config.cfg.PRE_060 $ORGADATA/cnf/extComm/config.cfg

mv $ORGADATA/cnf/reg/scp/zones/cf.old $ORGADATA/cnf/reg/scp
ssh mrte2@localhost 'source .profile;mv $ORGADATA/cnf/reg/scp/zones/cf.old $ORGADATA/cnf/reg/scp;cp $ORGADATA/cnf/extComm/config.cfg $ORGADATA/cnf/extComm/config.cfg.si-check-orgadatadanGelen;cp $ORGADATA/cnf/extComm/config.cfg.PRE_060 $ORGADATA/cnf/extComm/config.cfg' 
 

 
 echo komut: "ssh bas@10.248.68.128 'source .profile;si-check-orgadata --fix-data --fix-conf --fix-env --fix-struct ' > bas.si-check-orgadata.log 2>&1"
 ssh bas@10.248.68.128 'source .profile;si-check-orgadata --fix-data --fix-conf --fix-env --fix-struct ' > bas.si-check-orgadata.log 2>&1
hata=$(grep -v ':E:Old entry cnf/reg/scp/zones/cf.old replaced by symlinked should be checked.' bas.si-check-orgadata.log|egrep ':E:|:P:'|grep -v ':P:Errors occured in checking $ORGADATA.'|grep -v 'that do not belong here'|wc -l)
#hata2=$(grep 'that do not belong here' bas.si-check-orgadata.log|wc -l)
#if [[ $hata -ne 0||$hata2 -ne 1 ]]
if [[ $hata -ne 0 ]]
then
 echo   "si-check-orgadata basda hata verdi galiba. kontrol ediniz"
 cat bas.si-check-orgadata.log
 doMail "si-check-orgadata basda hata verdi galiba. kontrol ediniz"
 cleanup;exit
fi
 echo komut: "ssh bas@10.248.68.128 'source .profile;si-check-orgadata --fix-svn;echo ---;cs_client "Update Agile$(date +%Y%m%d%H%M)" submit;echo ---;'"
ssh bas@10.248.68.128 'source .profile;si-check-orgadata --fix-svn;echo ---;cs_client "Update Agile$(date +%Y%m%d%H%M)" submit;echo ---;'
 
echo Return To Previous Patch Files bitti. Restart ya da deploy yapilmadi. >out.txt
echo script bitis zamani:>> log
date >> log
date
echo
echo ---
echo -en "\n---" >>out.txt
ls -lrt $ORGADATA/cnf >>out.txt
ls -lrt ~/orgadata/cnf/cre/config_19700101000000.xml>>out.txt
echo >>out.txt
echo Terminate a subscriber for test:
gold_operation_handler terminate 05551234567 1 > /dev/null 2>&1
gold_operation_handler terminate 05551234568 1 
echo >>out.txt
echo Install Subscriber for test:
echo Install Subscriber for test: >>out.txt
 gold_operation_handler install 05551234568 TP_00019
 gold_operation_handler install 05551234567 TP_00019 >>out.txt 2>&1
 echo  >> out.txt
 #echo chk db: >>out.txt 
 #echo "idbm_print MrteSubscriberLookup 2>&1| grep 05551234567"  >>out.txt
 idbm_print MrteSubscriberLookup | grep 05551234567 >>out.txt 2>&1
 
 grep -oP ":SERVICE .DeployConfigBundle.IO.Output: \[Deployed=true" bascs_01_0?_CSLOG.txt
 
 grep -oP ":SERVICE .DeployConfigBundle.IO.Output: \[Deployed=true" bascs_01_0?_CSLOG.txt >> out.txt
 echo  Finished >> out.txt
 #echo Have a good day >> out.txt
 scp out.txt mrte1@10.248.68.122:/tmp
 cat maillist.txt |xargs echo > .mail
while read EMAIL_LIST
do
if [ ! -z "$EMAIL_LIST" ]
then
ssh mrte1@10.248.68.122 "source .profile;cat  /tmp/out.txt| mailx -s 'Return To Previous Patch Files sonucu - Agile Ortami' $EMAIL_LIST"
fi
done < .mail

for job in `cat pid.${sec}`
do
    /usr/bin/kill -9 $job 

done
rm pid.${sec}
ls -lrt  
 
sleep 1
echo
echo ---
echo grep -i cmdeployed mrte2OUPMLog.txt mrte1OUPMLog.txt 
grep -i cmdeployed mrte2OUPMLog.txt mrte1OUPMLog.txt 
ls -lrt $ORGADATA/cnf 
ls -lrt ~/orgadata/cnf/cre/config_19700101000000.xml
echo chk db:
idbm_print MrteSubscriberLookup | grep 05551234568


rm locked
