#! /usr/bin/bash

#AUT Productions
#produce Numbers till one exists in the same mrte with the script

while true; do 
msisdn0=$(cat no |head -1)
msisdn=$(expr $msisdn0 + 1)
echo $msisdn > no
msisdn=0$msisdn


gold_operation_handler terminate $msisdn 2  2>&1|grep ERROR || sleep 3

gold_operation_handler install $msisdn TP_00149 2>&1|grep ERROR && exit


 
aid=$(msisdn_to_accountid $msisdn )

if [[ $(echo $aid|grep ERR|wc -l) = 1 ]]
then
     
    echo trying again
else
	sleep 1
	gold_operation_handler reload $msisdn 1000  
	sleep 5
	echo $msisdn
    exit #!!!!!!!
 
fi
done
 
 

