#! /usr/bin/bash

#AUT Productions
#produce Number

 
msisdn0=$(cat nom |head -1)
msisdn=$(expr $msisdn0 + 1)
echo $msisdn > nom
msisdn=0$msisdn


 
echo trying to install the number 
gold_operation_handler install $msisdn TP_00149 2>&1|grep ERROR && gold_operation_handler install $msisdn TP_00149 2>&1|grep ERROR && gold_operation_handler install $msisdn TP_00149 2>&1|grep ERROR && exit

echo reloading
	sleep 2
	gold_operation_handler reload $msisdn 1000  2>&1 |grep ERROR && gold_operation_handler reload $msisdn 1000
	sleep 2
	echo $msisdn
  
 
 
 

