#! /usr/bin/bash


#Here CI80100 is Wrapped by AUT
serviceIDlerDosyasi=$1
workdir=/tmp/CI
cd $workdir
msisdn0=$(cat no |head -1)
msisdn=$(expr $msisdn0 + 1)
echo $msisdn > no
msisdn=0$msisdn

cleanup()

{
echo " ctrl+c?"

   for job in `cat pid80.*`
do
    /usr/bin/kill -9 $job 
	echo please ignore if it gives permission errors. no problem.
	ssh mrte2@localhost "/usr/bin/kill -9 $job "

done
rm pid80.* 
  return $?
}
 
control_c()
# run if user hits control-c
{
  #echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}
 
# trap keyboard interrupt (control-c)
trap control_c SIGINT

gold_operation_handler terminate $msisdn 2
sleep 1
gold_operation_handler install $msisdn TP_00149
sleep 1
gold_operation_handler reload $msisdn 1000  
sleep 5

mrteid=$(echo $ORGADATA|sed 's/\(.*\)\(.\)/\2/')
aid=$(msisdn_to_accountid $msisdn )

if [[ $(echo $aid|grep ERR|wc -l) = 1 ]]
then
    if [[ $mrteid = 1 ]]
    then          
	echo mrte2de
    ssh mrte2@localhost "source .profile 2>&1 > /dev/null;cd $workdir;./CI80100 $msisdn $serviceIDlerDosyasi 2>&1 |tee output$msisdn   "
	mv *$msisdn* log
    exit
    else
	echo mrte1de
    ssh mrte1@localhost "source .profile 2>&1 > /dev/null;cd $workdir;./CI80100 $msisdn $serviceIDlerDosyasi 2>&1 |tee output$msisdn "
	mv *$msisdn* log
    exit
    fi
fi
echo abone bu mrtede
  ./CI80100 $msisdn $serviceIDlerDosyasi 2>&1|tee output$msisdn
  mv *$msisdn* log
 
 
