#! /usr/bin/bash
 
if [[ $# -ne 4 && $# -ne 3  ]] 
    then 
	echo "illegal number of parameters"
	echo "Kullaným: $0 MSISDN ROPID bonusid  "
	echo "ornek kullanimlar:"
	echo "$0 05011011111 650 2260  "
	echo "$0 05011011111 650 2261  "
	echo "$0 05011011111 650 2262  "

  
	exit
fi
red='\e[0;33m' #33m sari :)
NC='\e[0m' # No Color
red2='\e[1;35m' #purple   
#export ORACLE_HOME=/export/home/mrte1/orgaroot/OracleClient11.2/client
msisdn=$1
serviceID=$2
bonusID=$3 #BONUS ID
calltype=$4
aid=$(msisdn_to_accountid $msisdn )
echo "AccountID:"$aid
echo "#d    $ and and and and = :AccountID '$aid' != :ID '1' != :ID '2' != :ID '3' != :ID '7' " | idbm_adb -s CreBalance

bonusName=$(  grep -oP "BLB_.*0${bonusID}" $ORGADATA/cnf/cre/config_19700101000000.xml|head -1)
echo "bonusName:"$bonusName
ropName=$(  grep -oP "PP_.*0${serviceID}" $ORGADATA/cnf/cre/config_19700101000000.xml|head -1)
echo "ROPName:"$ropName
echo "#u  :Value   $  and     = :AccountID '$aid'   = :ID '1'   & '1000'  " | idbm_adb -s CreBalance
gold_operation_handler package $msisdn $ropName  INACT   > /dev/null 2>&1
gold_operation_handler package $msisdn $ropName  ACT   2>&1 |grep ERROR
 
goldID=$(grep $bonusName $ORGADATA/cnf/cre/config_19700101000000.xml| grep -oP '(?<=<balance allow_negative="no" has_pockets="yes" id=")[^"]+')
later=$(mu_date -31)"000000"
 sonuc=$( echo "#s  :Value :End :Start $  and and   = :AccountID '$aid'   = :ID '$goldID' = :End '$later'   " | idbm_adb -s CreBalance|grep -v END|sed s/\'//g)

bonusAmount=$(echo $sonuc|cut   -f1 -d' ')
end=$(echo $sonuc|cut   -f2 -d' ')
start=$(echo $sonuc|cut   -f3 -d' ')

if [[ -n $bonusAmount ]]
then
	echo "Bonus amount: $bonusAmount " #$start $end
else
	echo "Bonus ID ya da Amount bulunamadý. Thanks for using."
	exit
fi

case "$calltype" in


dk|ses|DK|SES) 
 
echo "#u  :Value   $  and and   = :AccountID '$aid'   = :ID '$goldID' = :End '$later' & '60'  " | idbm_adb -s CreBalance
cd /export/home/mrte1/avea/USERS/zonder/call_simulation


now=$(date +%Y%m%d%H%M%S)

tarih=$now

ESC=$(echo '\033')
vi moc.req.start_tmp >/dev/null <<END
:%s/ANUM/$msisdn/g
:%s/BNUM/05012619181/g
:%s/CALLSTART/$tarih/g
:wq! moc.req.start
END

ESC=$(echo '\033')
vi moc.req.extend_tmp >/dev/null <<END  
:%s/ANUM/$msisdn/g    
:%s/BNUM/05012619181/g       
:%s/CALLSTART/$tarih/g
:%s/CDURATION/60/g
:wq! moc.req.extend
END

ESC=$(echo '\033')
vi moc.req.end_tmp >/dev/null <<END       
:%s/ANUM/$msisdn/g    
:%s/BNUM/05012619181/g       
:%s/CALLSTART/$tarih/g
:%s/CDURATION/60/g 
:wq! moc.req.end
END

./sim_comlayer -f MOC_1 -D  2>&1 |egrep 'ERROR|:E:|:P:'
    ;;
*) 
gold_operation_handler bonus $msisdn $bonusName -$bonusAmount $start $end 2>&1 |grep ERROR
   ;;
esac

 
echo "SMS9333 loglarýna bakýnýz 107 veya 108 ip'de.SMS9333te Loglarý gormek icin komut:"
		echo "tail -93 /argela/APSA/deploy/logs/APSA_CORE_H107_I0.log | grep ${msisdn}"
		echo "tail -93 /argela/APSA/deploy/logs/APSA_CORE_H108_I0.log | grep ${msisdn}"
		echo "#s  :Value   $  and and   = :AccountID '$aid'   = :ID '$goldID' = :End '$later'  " | idbm_adb -s CreBalance 
		
