#! /usr/bin/bash
  
msisdn=$1
serviceID=$2
 
AVEA_DIR=$ORGADATA/avea
if [[ $# -ne 2&&$# -ne 3 ]] 
    then 
	echo "illegal number of parameters"
	echo "Kullaným: $0 MSISDN serviceID   "
	echo "ornek kullanim:"
	echo ""
	echo "$0 05011011111 650"
	 

	exit
fi
#export ORACLE_HOME=/export/home/mrte1/orgaroot/OracleClient11.2/client
red='\e[0;33m' #33m sari :)
NC='\e[0m' # No Color
red2='\e[1;35m' #purple

ropName=$(  grep -oP "PP_.*0${serviceID}" $ORGADATA/cnf/cre/config_19700101000000.xml|head -1)   
bundleid=$(grep $ropName $ORGADATA/cnf/cre/config_19700101000000.xml|  grep -oP "(?<=<bundle id=\")[^\"]+"   )
echo bundleid:$bundleid    
aid=$(msisdn_to_accountid $msisdn )
echo "AccountID:"$aid
echo "#d    $ and and and and = :AccountID '$aid' != :ID '1' != :ID '2' != :ID '3' != :ID '7' " | idbm_adb -s CreBalance

echo "#u  :Value   $  and     = :AccountID '$aid'   = :ID '1'   & '1000'  " | idbm_adb -s CreBalance

/tmp/ulvi/killAllPacks $msisdn

#gold_operation_handler package $msisdn $ropName  INACT   > /dev/null 2>&1
gold_operation_handler package $msisdn $ropName  ACT   2>&1 |grep ERROR

tonight=$(mu_date -1)"000000"

echo "#u  :NextTriggerDate $  and = :AccountID '$aid' = :BundleID '$bundleid' & '$tonight' " | idbm_adb -s CreTrigger
 
 sec=$(date +%Y%m%d%H%M%S)
  
 


isUATevn=$(grep loghost /etc/hosts| grep 10.248.68.122|wc -l)
 if [[ $isUATevn -eq 0 ]] 
    then 
	 echo CheckMinPriceAgile:
	 satir=$(ssh bas@10.248.68.128 "grep -n 0${serviceID} /bas/orgadata/bas/cnf/domain-properties/basnc/productConfig/RecurringProduct.xml|cut -d: -f1")
	ssh bas@10.248.68.128 "tail   +$satir  /bas/orgadata/bas/cnf/domain-properties/basnc/productConfig/RecurringProduct.xml|head -45"
	else
	echo CheckMinPriceUAT:
	satir=$(ssh bas@10.248.68.123 "grep -n 0${serviceID} /bas/orgadata/bas/cnf/domain-properties/basnc/productConfig/RecurringProduct.xml|cut -d: -f1")
	ssh bas@10.248.68.123 "tail   +$satir  /bas/orgadata/bas/cnf/domain-properties/basnc/productConfig/RecurringProduct.xml|head -45"
fi

echo
echo -e "${red2}RopBalRem WA calistiriliyor. this may take a while"
echo
echo "pls check bonus priorities while waiting (90 for SMS all_dest)"
echo
for bonus in `echo "#s :ID   $ and and and and = :AccountID '$aid' != :ID '1' != :ID '2' != :ID '3' != :ID '7' " | idbm_adb -s CreBalance|grep -v END| sed "s/'//g" |sort|uniq`
do
	grep -i priority $ORGADATA/cnf/cre/config_19700101000000.xml|grep id=\"$bonus\"|grep -v CHARGE|grep -v cost_function|grep -v AUX
done
echo

 bash $ORGADATA/avea/work/RopAndBalanceReminderSMS/app/rop_and_balance_reminder_sms.sh
 
smsFile=$(ls -1t $ORGADATA/avea/work/RopAndBalanceReminderSMS/data/generated_sms_files | head -1 )
echo "Grep sonucu:"
grep $msisdn $ORGADATA/avea/work/RopAndBalanceReminderSMS/data/generated_sms_files/$smsFile

 logGrep=$(grep "9$msisdn;9333;000;" $ORGADATA/avea/work/RopAndBalanceReminderSMS/data/generated_sms_files/$smsFile|wc -l)
 
 if [[ $logGrep -eq 0 ]] 
    then 
	 echo -e "\e[7m  generated_sms_files'a gelmedi  ${NC}"
	
fi
  
