#! /usr/bin/bash
  
 #Author: AUT 
 #Purpose: I can
 
msisdn=$1
vol=$2
zaman=$3
cleanup()
# example cleanup function
{
echo " ctrl+c?"
echo

  egrep "$aid|$msisdn|MCPCDR-$cnt" /export/home/mrte2/orgadata/OHPQ/CRE-EFD.cre_0*/data*  /export/home/mrte1/orgadata/OHPQ/CRE-EFD.cre_0*/data*|grep $zaman|grep "<ServedParty>0$msisdn</ServedParty>"|tail -1 > ind  

    /usr/local/bin/grep -o '<ServedParty>[^\s]*</ServedParty>'  ind


   /usr/local/bin/grep -o '<OtherParty>[^\s]*</OtherParty>'  ind
      /usr/local/bin/grep -o '<CallDuration>[^\s]*</CallDuration>'  ind
           /usr/local/bin/grep -o '<duration>[^\s]*</duration><allowed>[^\s]*</allowed>'  ind

                 /usr/local/bin/grep -o '"charge"/><start>[^\s]*</start>'  ind
           /usr/local/bin/grep -o 'delta_source="[0-9.]*"'  ind
           echo Bunlarin toplami kadar ucretlendi:
           echo -e '\e[1;35m'
         /usr/local/bin/grep -oP 'charged_target="[0-9.]*" code="[^\s]*"'  ind
          echo -e '\e[0m'

  return $?
}

control_c()
# run if user hits control-c
{
  #echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}

# trap keyboard interrupt (control-c)
trap control_c SIGINT
 
if [[ $# -ne 2 && $# -ne 3 && $# -ne 4 ]] 
    then 
        echo "illegal number of parameters"
        echo "Kullaným: $0 MSISDN miktar zaman "
		echo "4th parameter should be -s for no return"
        echo "ornek kullanim:"
        echo ""
        echo "$0 5019144950 102400 20150101235959"

        exit
fi


#export ORACLE_HOME=/export/home/mrte1/orgaroot/OracleClient11.2/client
red='\e[0;33m' #33m sari :)
NC='\e[0m' # No Color
red2='\e[1;35m' #purple
cnt=$(cat counter)
aid=$(msisdn_to_accountid $msisdn )
 sed "s|5561045118|$msisdn|" /tmp/ulvi/cdr/MCPCDR-4385,1423781729_21644_1984446.cdr.internetauto   > tmpdata
sed "s|DURATION|$vol|" tmpdata > tmp2
sec=$(date +%Y%m%d%H%M%S)
sed "s|START|$zaman|" tmp2 > $ORGADATA/peg/brf_01/ready/DATA/MCPCDR-${cnt},1423781729_21644_1984446.cdr

cnt=$(expr $cnt + 1)
echo $cnt > counter

if [[ $# -ne 4    ]] 
    then 
        find $ORGADATA/log/ /export/home/mrte2/orgadata/OHPQ/CRE-EFD.cre_0*  /export/home/mrte1/orgadata/OHPQ/CRE-EFD.cre_0* | egrep 'RTE0|data.0' | egrep -v 'CRELOG|logger|gz'  | xargs tail -f -n 0 | egrep "$aid|$msisdn|MCPCDR-$cnt"
fi

