#! /usr/bin/bash
 
if [[ $# -ne 2 ]] 
    then 
	echo "illegal number of parameters"
	echo "Kullaným: $0 MSISDN   bonusid  "
	echo "ornek kullanimlar:"
	echo "$0 05011011111   2260  "
	 
  
	exit
fi
red='\e[0;33m' #33m sari :)
NC='\e[0m' # No Color
red2='\e[1;35m' #purple   
#export ORACLE_HOME=/export/home/mrte1/orgaroot/OracleClient11.2/client
msisdn=$1
bonusID=$2 
aid=$(msisdn_to_accountid $msisdn )
echo "AccountID:"$aid

 
bonusName=$(  grep -oP "BL._.*0${bonusID}" $ORGADATA/cnf/cre/config_19700101000000.xml|head -1)
echo "bonusName:"$bonusName
 

goldID=$(grep $bonusName $ORGADATA/cnf/cre/config_19700101000000.xml| grep -oP '(?<=<balance allow_negative="no" has_pockets="yes" id=")[^"]+')
#later=$(mu_date -31)"000000"
#bonusAmount=$(echo "#s  :Value $  and and   = :AccountID '$aid'   = :ID '$goldID' = :End '$later'   " | idbm_adb -s CreBalance|grep -v END|sed s/\'//g)
echo DEL:$goldID
echo "#d    $  and and and and and = :AccountID '$aid'   = :ID '$goldID' != :ID '1' != :ID '2' != :ID '3' != :ID '7' " | idbm_adb -s CreBalance

