#! /usr/bin/bash
 
 
cleanup()
# example cleanup function
{
echo " ctrl+c?"

   for job in `cat pid.${sec}`
do
    /usr/bin/kill -9 $job 

done
rm pid.${sec}
sleep 3
  return $?
}
 
control_c()
# run if user hits control-c
{
  #echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}
 
# trap keyboard interrupt (control-c)
trap control_c SIGINT

msisdn=$1
serviceID=$2
price=$3
AVEA_DIR=$ORGADATA/avea
if [[ $# -ne 2&&$# -ne 3 ]] 
    then 
	echo "illegal number of parameters"
	echo "Kullaným: $0 MSISDN serviceID yenilemeUcreti "
	echo "ornek kullanim:"
	echo ""
	echo "$0 05011011111 650"
	echo "$0 05011011111 650 17"

	exit
fi
#export ORACLE_HOME=/export/home/mrte1/orgaroot/OracleClient11.2/client
red='\e[0;33m' #33m sari :)
NC='\e[0m' # No Color
red2='\e[1;35m' #purple

ropName=$(  grep -oP "PP_.*0${serviceID}" $ORGADATA/cnf/cre/config_19700101000000.xml|head -1)         
aid=$(msisdn_to_accountid $msisdn )


echo "AccountID:"$aid
echo "#d    $ and and and and = :AccountID '$aid' != :ID '1' != :ID '2' != :ID '3' != :ID '7' " | idbm_adb -s CreBalance
#echo "#d    $   = :AccountID '$aid'  " | idbm_adb -s CreTrigger
echo "#u  :Value   $  and     = :AccountID '$aid'   = :ID '1'   & '1000'  " | idbm_adb -s CreBalance

#gold_operation_handler package $msisdn $ropName  INACT   > /dev/null 2>&1
/tmp/ulvi/killAllPacks $msisdn
gold_operation_handler package $msisdn $ropName  ACT   2>&1 |grep ERROR
kalanPara=$(echo "#s  :Value   $  and     = :AccountID '$aid'   = :ID '1'      " | idbm_adb -s CreBalance|grep -v END|sed s/\'//g|perl -nl -MPOSIX -e 'print ceil($_);') 
 sec=$(date +%Y%m%d%H%M%S)
 bundleid=$(grep $ropName $ORGADATA/cnf/cre/config_19700101000000.xml|  grep -oP "(?<=<bundle id=\")[^\"]+"   )
 echo bundleid:$bundleid  
 ruleid=$(echo "#s  :RuleID $  and = :AccountID '$aid' = :BundleID '$bundleid'   " | idbm_adb -s CreTrigger|grep -v END|sed s/\'//g)
echo ruleid:$ruleid
if [[ $kalanPara -ne `expr 1000 - $price` ]]
then
	echo -e "\e[7m Kayit ucreti yanlis.  ${NC}"
	echo $kalanPara
fi

 
#eksikUcret=$(echo  "$price-0.0001"|bc -l) 
later=$(mu_date -31)"000000"


			#echo "#u  :Value   $  and     = :AccountID '$aid'   = :ID '1'   & '$price'  " | idbm_adb -s CreBalance
 

 	echo -e "******----------------RENEW TEST EDILIYO--------------------******${NC}"
	#echo -e "${red}******--------------------------------------------------------------******${NC}"
 today_isodate=$(ots_date -S `date +%'Y'%'m'%'d'000000` +31d)
 
 echo -e "${red2}cre_batch kosuluyor"
#$ORGAROOT/run/bin/cre_batch -e $today_isodate -r 70,$ruleid  -DID BAT.manually  -a $aid > /dev/null 2>&1
 cre_batch -e $today_isodate -DID BAT.manually
kalanPara=$(echo "#s  :Value   $  and     = :AccountID '$aid'   = :ID '1'      " | idbm_adb -s CreBalance|grep -v END|sed s/\'//g|perl -nl -MPOSIX -e 'print ceil($_);') 
if [[ $kalanPara -ne `expr 1000 - 2 \* $price` ]]
then
	echo -e "\e[7m Yenileme ucreti yanlis.  ${NC}"
	echo $kalanPara
fi
mrteid=$(echo $ORGADATA|sed 's/\(.*\)\(.\)/\2/')
if [[ $mrteid -eq 2 ]] 
    then 
	ssh mrte1@localhost "source .profile;subsquery $msisdn b || subsquery $msisdn b"   
	else
	subsquery $msisdn b || subsquery $msisdn b
	
fi
 
echo "#s :ID :Value :Start :End  $ and and and and and = :AccountID '$aid' != :ID '1' != :ID '2' != :ID '3' != :ID '7' != :Value '0' " | idbm_adb -s CreBalance


 today_isodate=$(ots_date -S `date +%'Y'%'m'%'d'000000` +61d)
 
 echo -e "${red2}cre_batch kosuluyor2 $today_isodate"
#$ORGAROOT/run/bin/cre_batch -e $today_isodate -r 70,$ruleid  -DID BAT.manually  -a $aid > /dev/null 2>&1
 cre_batch -e $today_isodate -DID BAT.manually
 
 if [[ $mrteid -eq 2 ]] 
    then 
	ssh mrte1@localhost "source .profile;subsquery $msisdn b || subsquery $msisdn b || subsquery $msisdn b"   
	else
	subsquery $msisdn b || subsquery $msisdn b || subsquery $msisdn b
	
fi


 today_isodate=$(ots_date -S `date +%'Y'%'m'%'d'000000` +91d)
 
 echo -e "${red2}cre_batch kosuluyor2 $today_isodate"
#$ORGAROOT/run/bin/cre_batch -e $today_isodate -r 70,$ruleid  -DID BAT.manually  -a $aid > /dev/null 2>&1
 cre_batch -e $today_isodate -DID BAT.manually
 
 if [[ $mrteid -eq 2 ]] 
    then 
	ssh mrte1@localhost "source .profile;subsquery $msisdn b || subsquery $msisdn b || subsquery $msisdn b"   
	else
	subsquery $msisdn b || subsquery $msisdn b || subsquery $msisdn b
	
fi
