#! /usr/bin/bash
  
 #Copyright: AUT Productions
msisdn=$1
vol=$2
other=$3
 
if [[ $# -ne 3 && $# -ne 4 && $# -ne 5  ]] 
    then 
	echo "illegal number of parameters"
	echo "Kullaným: $0 MSISDN  saniye digerNo zaman [-s] "
	echo "-s means silent and returning back to caller"
	echo "ornek kullanim:"
	echo ""
	echo "$0 05019144950 60  08888121341 20150808235959"

	exit
fi


#export ORACLE_HOME=/export/home/mrte1/orgaroot/OracleClient11.2/client
red='\e[0;33m' #33m sari :)
NC='\e[0m' # No Color
red2='\e[1;35m' #purple
sec=$(date +%Y%m%d%H%M%S)
sec=$4
cnt=$(cat counterindata)
aid=$(msisdn_to_accountid $msisdn )
 sed "s|05030124017|$msisdn|" /tmp/ulvi/cdr/MCPCDR-2802,1411974557_19745_1697091.cdr.11880indata1   > tmpdata2
sed "s|DURATION|$vol|" tmpdata2 > tmp2
sed "s|11880|$other|" tmp2 > tmp3
sed "s|START|$sec|" tmp3 > $ORGADATA/peg/brf_01/ready/DATA/MCPCDR-${cnt},1411974557_19745_1697091.cdr

cnt=$(expr $cnt + 1)
echo $cnt > counterindata

if [[ $# -ne 5    ]] 
    then 
	find $ORGADATA/log/ /export/home/mrte2/orgadata/OHPQ/CRE-EFD.cre_0*  /export/home/mrte1/orgadata/OHPQ/CRE-EFD.cre_0* | egrep 'RTE0|data.0' | egrep -v 'CRELOG|logger|gz'  | xargs tail -f -n 0 | egrep "$aid|$msisdn|MCPCDR-$cnt"
	 #egrep "$aid|$msisdn|MCPCDR-$cnt" /export/home/mrte2/orgadata/OHPQ/CRE-EFD.cre_0*/data*  /export/home/mrte1/orgadata/OHPQ/CRE-EFD.cre_0*/data*  |/usr/local/bin/grep -oP 'delta_target=".*"'
	#grep -o 'delta_target=".*"' logindata1
	
fi

	 
